In [1]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\User\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [12]:
a[2] = 10

In [29]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [25]:
n[0, 1] = 20

In [30]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [34]:
n[2] = [1, 1, 1]

In [35]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [40]:
n[:, 2] = [0, 1, 2]

In [41]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [47]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [48]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [50]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
a + 1

array([1, 2, 3, 4, 5])

In [63]:
b = (10 + (a * 2)) ** 2 /100

In [64]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [67]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [68]:
a >= 2

array([False, False,  True,  True,  True])

In [70]:
a > b

array([False, False,  True,  True,  True])

In [71]:
a[a > b]

array([2, 3, 4])

In [72]:
a.min()

np.int64(0)

In [73]:
a.max()

np.int64(4)

In [74]:
a.sum()

np.int64(10)

In [75]:
a.mean()

np.float64(2.0)

In [80]:
a.std()

np.float64(1.4142135623730951)

In [88]:
n.mean()

np.float64(3.888888888888889)