In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__


'3.0.3'

In [11]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [15]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [23]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [17]:
df["fuel_type"].nunique()

3

In [18]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [30]:
df.groupby("origin").fuel_efficiency_mpg.max()["Asia"]

np.float64(41.2)

In [33]:
df.horsepower.median()

np.float64(254.0)

In [44]:
mode = df.horsepower.mode()
mode

0    252.0
Name: horsepower, dtype: float64

In [45]:
df.horsepower = df.horsepower.fillna(mode)

In [46]:
df.horsepower.isnull().sum()

np.int64(0)

In [47]:
df.horsepower.median()

np.float64(252.0)

In [55]:
X = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [61]:
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [63]:
XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [64]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [71]:
w = np.linalg.inv(XTX).dot(XT).dot(y)
w

array([0.13644777, 0.2327492 ])

In [72]:
w.sum()

np.float64(0.36919696904927707)